# Generated by Django 3.2.3 on 2021-07-04 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название фильма')),
                ('logo', models.ImageField(upload_to='images', verbose_name='Логотип фильма')),
                ('youtube_trailer_url', models.URLField(unique=True, verbose_name='Ссылка на трейлер фильма в YouTube')),
                ('year', models.PositiveIntegerField(verbose_name='Год выхода фильма')),
                ('rating', models.FloatField(verbose_name='Рейтинг фильма')),
                ('producer', models.CharField(max_length=5000, verbose_name='Режиссёр(-ы) фильма')),
                ('description', models.TextField(verbose_name='Описание фильма')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название сериала')),
                ('logo', models.ImageField(upload_to='images', verbose_name='Логотип сериала')),
                ('youtube_trailer_url', models.URLField(unique=True, verbose_name='Ссылка на трейлер сериала в YouTube')),
                ('year', models.PositiveIntegerField(verbose_name='Год выхода сериала')),
                ('rating', models.FloatField(verbose_name='Рейтинг сериала')),
                ('producer', models.CharField(max_length=5000, verbose_name='Режиссёр(-ы) сериала')),
                ('description', models.TextField(verbose_name='Описание сериала')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SeriesComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000, verbose_name='Заголовок комментария')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата комментария')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KinomonsterApp.series', verbose_name='Сериал')),
            ],
            options={
                'verbose_name': 'Комментарий к сериалу',
                'verbose_name_plural': 'Комментарии к сериалам',
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='FilmComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000, verbose_name='Заголовок комментария')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата комментария')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='KinomonsterApp.film', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Комментарий к фильму',
                'verbose_name_plural': 'Комментарии к фильмам',
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000, null=True, verbose_name='Заголовок текста')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор текста')),
            ],
        ),
    ]
