# Generated by Django 3.2.3 on 2021-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinomonsterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почтовый адрес автора текста'),
        ),
    ]
